/**
 * Script de génération automatique de 500 machines XState
 * Génère des machines pour 13 domaines légaux belges
 */

import * as fs from 'fs';
import * as path from 'path';

interface MachineDefinition {
  id: string;
  name: string;
  category: string;
  folder: string;
  description: string;
  states: string[];
  contextFields: Record<string, string>;
  events: string[];
}

// Définition des 500 machines à créer
const machinesDefinitions: MachineDefinition[] = [
  // SANTÉ ET SOINS MÉDICAUX (50 machines)
  { id: 'consultationSpecialiste', name: 'Consultation Spécialiste', category: 'health', folder: 'health', description: 'Consultation médicale spécialisée', states: ['inactif', 'verification', 'rdv', 'consultation', 'termine'], contextFields: { patient: 'Patient | null', specialite: 'string' }, events: ['DEMARRER', 'CONFIRMER_RDV', 'CONSULTER'] },
  { id: 'urgencesHospitalieres', name: 'Urgences Hospitalières', category: 'health', folder: 'health', description: 'Prise en charge aux urgences', states: ['attente', 'triage', 'examen', 'traitement', 'sortie'], contextFields: { patient: 'Patient | null', gravite: 'string' }, events: ['ARRIVEE', 'TRIAGE', 'TRAITER'] },
  { id: 'chirurgieAmbulat oire', name: 'Chirurgie Ambulatoire', category: 'health', folder: 'health', description: 'Intervention chirurgicale en ambulatoire', states: ['consultation', 'preparation', 'intervention', 'reveil', 'sortie'], contextFields: { patient: 'Patient | null', typeIntervention: 'string' }, events: ['PLANIFIER', 'INTERVENIR', 'SORTIR'] },
  { id: 'examensLaboratoire', name: 'Examens de Laboratoire', category: 'health', folder: 'health', description: 'Analyses médicales en laboratoire', states: ['prescription', 'prelevement', 'analyse', 'resultats'], contextFields: { patient: 'Patient | null', typeExamen: 'string' }, events: ['PRESCRIRE', 'PRELEVER', 'ANALYSER'] },
  { id: 'radiologieMedicale', name: 'Radiologie Médicale', category: 'health', folder: 'health', description: 'Examens radiologiques', states: ['prescription', 'rdv', 'examen', 'interpretation', 'resultat'], contextFields: { patient: 'Patient | null', typeRadio: 'string' }, events: ['PRESCRIRE', 'EXAMINER', 'INTERPRETER'] },
  { id: 'kinesitherapie', name: 'Kinésithérapie', category: 'health', folder: 'health', description: 'Séances de kinésithérapie', states: ['prescription', 'evaluation', 'traitement', 'suivi'], contextFields: { patient: 'Patient | null', nbSeances: 'number' }, events: ['PRESCRIRE', 'EVALUER', 'TRAITER'] },
  { id: 'soinsInfirmiers', name: 'Soins Infirmiers à Domicile', category: 'health', folder: 'health', description: 'Soins infirmiers à domicile', states: ['prescription', 'planification', 'execution', 'rapport'], contextFields: { patient: 'Patient | null', frequence: 'string' }, events: ['PRESCRIRE', 'PLANIFIER', 'SOIGNER'] },
  { id: 'materniteAccouchement', name: 'Maternité et Accouchement', category: 'health', folder: 'health', description: 'Suivi grossesse et accouchement', states: ['suivi', 'admission', 'accouchement', 'postnatal', 'sortie'], contextFields: { patiente: 'Patient | null', termeGrossesse: 'number' }, events: ['ADMISSION', 'ACCOUCHER', 'SORTIR'] },
  { id: 'pediatrieConsultation', name: 'Consultation Pédiatrique', category: 'health', folder: 'health', description: 'Consultations pédiatriques', states: ['rdv', 'examen', 'diagnostic', 'traitement'], contextFields: { enfant: 'Patient | null', age: 'number' }, events: ['CONSULTER', 'DIAGNOSTIQUER', 'PRESCRIRE'] },
  { id: 'vaccinationEnfants', name: 'Vaccination Enfants', category: 'health', folder: 'health', description: 'Programme de vaccination pédiatrique', states: ['verification', 'preparation', 'injection', 'surveillance'], contextFields: { enfant: 'Patient | null', vaccin: 'string' }, events: ['VERIFIER', 'VACCINER', 'SURVEILLER'] },
  { id: 'dentisteSoins', name: 'Soins Dentaires', category: 'health', folder: 'health', description: 'Soins dentaires et orthodontie', states: ['consultation', 'diagnostic', 'devis', 'traitement', 'suivi'], contextFields: { patient: 'Patient | null', typeSoin: 'string' }, events: ['CONSULTER', 'DEVIS', 'TRAITER'] },
  { id: 'ophtalmologie', name: 'Ophtalmologie', category: 'health', folder: 'health', description: 'Consultations ophtalmologiques', states: ['examen', 'prescription', 'lunettes'], contextFields: { patient: 'Patient | null', correction: 'string' }, events: ['EXAMINER', 'PRESCRIRE'] },
  { id: 'psychotherapie', name: 'Psychothérapie', category: 'health', folder: 'health', description: 'Séances de psychothérapie', states: ['premiere-seance', 'traitement', 'suivi', 'termine'], contextFields: { patient: 'Patient | null', nbSeances: 'number' }, events: ['DEMARRER', 'SEANCE', 'TERMINER'] },
  { id: 'psychiatrieConsultation', name: 'Consultation Psychiatrique', category: 'health', folder: 'health', description: 'Suivi psychiatrique', states: ['evaluation', 'diagnostic', 'traitement', 'suivi'], contextFields: { patient: 'Patient | null', pathologie: 'string' }, events: ['EVALUER', 'DIAGNOSTIQUER', 'SUIVRE'] },
  { id: 'addictologiePriseCharge', name: 'Addictologie', category: 'health', folder: 'health', description: 'Prise en charge des addictions', states: ['evaluation', 'desintoxication', 'suivi', 'reinsertion'], contextFields: { patient: 'Patient | null', typeAddiction: 'string' }, events: ['EVALUER', 'DESINTOXIQUER', 'SUIVRE'] },
  { id: 'dialyseRenale', name: 'Dialyse Rénale', category: 'health', folder: 'health', description: 'Séances de dialyse', states: ['preparation', 'dialyse', 'surveillance', 'termine'], contextFields: { patient: 'Patient | null', frequenceHebdo: 'number' }, events: ['PREPARER', 'DIALYSER'] },
  { id: 'chimiotherapie', name: 'Chimiothérapie', category: 'health', folder: 'health', description: 'Traitement par chimiothérapie', states: ['consultation', 'preparation', 'administration', 'surveillance'], contextFields: { patient: 'Patient | null', protocole: 'string' }, events: ['PLANIFIER', 'ADMINISTRER', 'SURVEILLER'] },
  { id: 'radiotherapie', name: 'Radiothérapie', category: 'health', folder: 'health', description: 'Traitement par radiothérapie', states: ['planification', 'reperage', 'traitement', 'suivi'], contextFields: { patient: 'Patient | null', nbSeances: 'number' }, events: ['PLANIFIER', 'TRAITER'] },
  { id: 'reanimationSoinsIntensifs', name: 'Réanimation et Soins Intensifs', category: 'health', folder: 'health', description: 'Prise en charge en réanimation', states: ['admission', 'stabilisation', 'traitement', 'sortie'], contextFields: { patient: 'Patient | null', gravite: 'string' }, events: ['ADMETTRE', 'STABILISER', 'SORTIR'] },
  { id: 'greffe Organe', name: 'Greffe d\'Organe', category: 'health', folder: 'health', description: 'Procédure de transplantation', states: ['liste-attente', 'compatible', 'intervention', 'suivi'], contextFields: { patient: 'Patient | null', organe: 'string' }, events: ['INSCRIRE', 'GREFFER', 'SUIVRE'] },
  { id: 'reeducationFonctionnelle', name: 'Rééducation Fonctionnelle', category: 'health', folder: 'health', description: 'Centre de rééducation', states: ['admission', 'bilan', 'reeducation', 'evaluation'], contextFields: { patient: 'Patient | null', duree: 'number' }, events: ['ADMETTRE', 'REEDUQUER'] },
  { id: 'geriatrieConsultation', name: 'Gériatrie', category: 'health', folder: 'health', description: 'Médecine gériatrique', states: ['evaluation', 'plan-soin', 'traitement', 'suivi'], contextFields: { patient: 'Patient | null', age: 'number' }, events: ['EVALUER', 'TRAITER'] },
  { id: 'soinsLongueDuree', name: 'Soins de Longue Durée', category: 'health', folder: 'health', description: 'Établissement de soins long terme', states: ['admission', 'installation', 'soins-quotidiens', 'suivi'], contextFields: { patient: 'Patient | null', dependance: 'string' }, events: ['ADMETTRE', 'SOIGNER'] },
  { id: 'soinsPalliatifs', name: 'Soins Palliatifs', category: 'health', folder: 'health', description: 'Accompagnement en fin de vie', states: ['evaluation', 'soulagement', 'accompagnement', 'deces'], contextFields: { patient: 'Patient | null', pronostic: 'string' }, events: ['EVALUER', 'SOULAGER'] },
  { id: 'medecineTravail', name: 'Médecine du Travail', category: 'health', folder: 'health', description: 'Surveillance médicale professionnelle', states: ['visite-embauche', 'visite-periodique', 'bilan'], contextFields: { travailleur: 'Patient | null', poste: 'string' }, events: ['EXAMINER', 'APTITUDE'] },
  { id: 'secourismeFormation', name: 'Formation Secourisme', category: 'health', folder: 'health', description: 'Formation aux premiers secours', states: ['inscription', 'formation', 'examen', 'certification'], contextFields: { participant: 'string', niveau: 'string' }, events: ['INSCRIRE', 'FORMER', 'CERTIFIER'] },
  { id: 'donSang', name: 'Don du Sang', category: 'health', folder: 'health', description: 'Procédure de don de sang', states: ['questionnaire', 'examen', 'prelevement', 'repos'], contextFields: { donneur: 'Patient | null', groupeSanguin: 'string' }, events: ['VERIFIER', 'PRELEVER'] },
  { id: 'donsOrganes', name: 'Inscription Dons d\'Organes', category: 'health', folder: 'health', description: 'Enregistrement comme donneur', states: ['information', 'consentement', 'enregistrement'], contextFields: { personne: 'string', organes: 'string[]' }, events: ['INFORMER', 'CONSENTIR', 'ENREGISTRER'] },
  { id: 'pmiFamille', name: 'PMI et Protection Maternelle', category: 'health', folder: 'health', description: 'Suivi PMI', states: ['inscription', 'consultations', 'vaccinations', 'suivi'], contextFields: { enfant: 'Patient | null', parents: 'string' }, events: ['INSCRIRE', 'CONSULTER'] },
  { id: 'planningFamilial', name: 'Planning Familial', category: 'health', folder: 'health', description: 'Centre de planning familial', states: ['consultation', 'conseil', 'prescription'], contextFields: { personne: 'Patient | null', demande: 'string' }, events: ['CONSULTER', 'CONSEILLER'] },
  { id: 'ivrInterruptionGrossesse', name: 'IVG (Interruption Volontaire de Grossesse)', category: 'health', folder: 'health', description: 'Procédure IVG légale', states: ['consultation', 'delai-reflexion', 'intervention', 'suivi'], contextFields: { patiente: 'Patient | null', termeGrossesse: 'number' }, events: ['CONSULTER', 'INTERVENIR'] },
  { id: 'procreationAssistee', name: 'Procréation Médicalement Assistée', category: 'health', folder: 'health', description: 'PMA et FIV', states: ['bilan-fertilite', 'protocole', 'stimulation', 'ponction', 'transfert'], contextFields: { couple: 'string', tentative: 'number' }, events: ['BILAN', 'STIMULER', 'TRANSFERER'] },
  { id: 'depistagesCancers', name: 'Dépistages Cancers', category: 'health', folder: 'health', description: 'Programme de dépistage', states: ['invitation', 'examen', 'resultat', 'suivi'], contextFields: { patient: 'Patient | null', typeCancer: 'string' }, events: ['INVITER', 'DEPISTER'] },
  { id: 'bilansPreventifs', name: 'Bilans de Santé Préventifs', category: 'health', folder: 'health', description: 'Bilans de santé réguliers', states: ['programmation', 'examens', 'resultats', 'conseils'], contextFields: { patient: 'Patient | null', age: 'number' }, events: ['PROGRAMMER', 'EXAMINER'] },
  { id: 'nutritionDietetique', name: 'Consultation Nutrition', category: 'health', folder: 'health', description: 'Suivi nutritionnel', states: ['bilan', 'programme', 'suivi', 'evaluation'], contextFields: { patient: 'Patient | null', objectif: 'string' }, events: ['EVALUER', 'PROGRAMMER'] },
  { id: 'allergologieTests', name: 'Tests Allergologiques', category: 'health', folder: 'health', description: 'Dépistage allergies', states: ['anamnese', 'tests-cutanes', 'resultats', 'traitement'], contextFields: { patient: 'Patient | null', allergenes: 'string[]' }, events: ['INTERROGER', 'TESTER'] },
  { id: 'dermatologieConsultation', name: 'Dermatologie', category: 'health', folder: 'health', description: 'Consultations dermatologiques', states: ['examen', 'diagnostic', 'traitement', 'suivi'], contextFields: { patient: 'Patient | null', pathologie: 'string' }, events: ['EXAMINER', 'TRAITER'] },
  { id: 'cardiologieConsultation', name: 'Cardiologie', category: 'health', folder: 'health', description: 'Suivi cardiologique', states: ['consultation', 'examens', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', facteurs Risque: 'string[]' }, events: ['CONSULTER', 'ECG', 'TRAITER'] },
  { id: 'pneumologieConsultation', name: 'Pneumologie', category: 'health', folder: 'health', description: 'Maladies respiratoires', states: ['consultation', 'exploration', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', symptomes: 'string' }, events: ['CONSULTER', 'EXPLORER'] },
  { id: 'gastroenterologieConsultation', name: 'Gastro-entérologie', category: 'health', folder: 'health', description: 'Maladies digestives', states: ['consultation', 'examens', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', symptomes: 'string' }, events: ['CONSULTER', 'ENDOSCOPIE'] },
  { id: 'endocrinologieConsultation', name: 'Endocrinologie', category: 'health', folder: 'health', description: 'Troubles hormonaux', states: ['consultation', 'bilan-hormonal', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', trouble: 'string' }, events: ['CONSULTER', 'BILAN'] },
  { id: 'rhumatologieConsultation', name: 'Rhumatologie', category: 'health', folder: 'health', description: 'Maladies ostéo-articulaires', states: ['consultation', 'imagerie', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', douleurs: 'string' }, events: ['CONSULTER', 'EXAMINER'] },
  { id: 'neurologieConsultation', name: 'Neurologie', category: 'health', folder: 'health', description: 'Maladies neurologiques', states: ['consultation', 'examens', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', symptomes: 'string' }, events: ['CONSULTER', 'IRM'] },
  { id: 'urologieConsultation', name: 'Urologie', category: 'health', folder: 'health', description: 'Pathologies urologiques', states: ['consultation', 'examens', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', symptomes: 'string' }, events: ['CONSULTER', 'ECHOGRAPHIE'] },
  { id: 'gynecologieConsultation', name: 'Gynécologie', category: 'health', folder: 'health', description: 'Suivi gynécologique', states: ['consultation', 'examen', 'frottis', 'suivi'], contextFields: { patiente: 'Patient | null', age: 'number' }, events: ['CONSULTER', 'FROTTIS'] },
  { id: 'orl Consultation', name: 'ORL', category: 'health', folder: 'health', description: 'Oto-rhino-laryngologie', states: ['consultation', 'examen', 'diagnostic', 'traitement'], contextFields: { patient: 'Patient | null', symptomes: 'string' }, events: ['CONSULTER', 'AUDIOMETRIE'] },
  { id: 'podologie', name: 'Podologie', category: 'health', folder: 'health', description: 'Soins podologiques', states: ['consultation', 'diagnostic', 'soins', 'ortheses'], contextFields: { patient: 'Patient | null', probleme: 'string' }, events: ['CONSULTER', 'SOIGNER'] },
  { id: 'orthophonie', name: 'Orthophonie', category: 'health', folder: 'health', description: 'Rééducation orthophonique', states: ['bilan', 'programme', 'seances', 'evaluation'], contextFields: { patient: 'Patient | null', trouble: 'string' }, events: ['EVALUER', 'REEDUQUER'] },
  { id: 'ergotherapie', name: 'Ergothérapie', category: 'health', folder: 'health', description: 'Rééducation par ergothérapie', states: ['evaluation', 'objectifs', 'reeducation', 'autonomie'], contextFields: { patient: 'Patient | null', limitation: 'string' }, events: ['EVALUER', 'REEDUQUER'] },
  { id: 'psychomotricite', name: 'Psychomotricité', category: 'health', folder: 'health', description: 'Thérapie psychomotrice', states: ['bilan', 'prise-en-charge', 'suivi'], contextFields: { patient: 'Patient | null', trouble: 'string' }, events: ['EVALUER', 'TRAITER'] },

  // JUSTICE ET PROCÉDURES JUDICIAIRES (50 machines)
  { id: 'plainteCommissariat', name: 'Dépôt de Plainte', category: 'justice', folder: 'justice', description: 'Dépôt plainte au commissariat', states: ['reception', 'audition', 'redaction-pv', 'transmission-parquet'], contextFields: { plaignant: 'string', faits: 'string' }, events: ['DEPOSER', 'AUDITION', 'TRANSMETTRE'] },
  { id: 'gardeVue', name: 'Garde à Vue', category: 'justice', folder: 'justice', description: 'Procédure de garde à vue', states: ['arrestation', 'notification-droits', 'audition', 'liberation-ou-detention'], contextFields: { suspect: 'string', duree: 'number' }, events: ['ARRETER', 'AUDITION', 'DECIDER'] },
  { id: 'instructionJudiciaire', name: 'Instruction Judiciaire', category: 'justice', folder: 'justice', description: 'Phase d\'instruction pénale', states: ['ouverture', 'investigations', 'auditions', 'cloture'], contextFields: { dossier: 'string', jugeInstruction: 'string' }, events: ['OUVRIR', 'INVESTIGUER', 'CLOTURER'] },
  { id: 'miseExamen', name: 'Mise en Examen', category: 'justice', folder: 'justice', description: 'Mise en examen d\'un suspect', states: ['indices', 'convocation', 'interrogatoire', 'decision'], contextFields: { personne: 'string', charges: 'string[]' }, events: ['CONVOQUER', 'INTERROGER', 'DECIDER'] },
  { id: 'detentionProvisoire', name: 'Détention Provisoire', category: 'justice', folder: 'justice', description: 'Placement en détention avant jugement', states: ['requete', 'debat-contradictoire', 'decision', 'detention'], contextFields: { prevenu: 'string', duree: 'number' }, events: ['REQUERIR', 'DEBATTRE', 'ORDONNER'] },
  { id: 'controleJudiciaire', name: 'Contrôle Judiciaire', category: 'justice', folder: 'justice', description: 'Mesure alternative à la détention', states: ['ordonnance', 'obligations', 'controle', 'respect-ou-revocation'], contextFields: { personne: 'string', obligations: 'string[]' }, events: ['ORDONNER', 'CONTROLER'] },
  { id: 'tribunalCorrectionnelAudience', name: 'Tribunal Correctionnel', category: 'justice', folder: 'justice', description: 'Procès correctionnel', states: ['renvoi', 'audience', 'plaidoiries', 'delibere', 'jugement'], contextFields: { prevenu: 'string', infraction: 'string' }, events: ['RENVOYER', 'PLAIDER', 'JUGER'] },
  { id: 'courAssises', name: 'Cour d\'Assises', category: 'justice', folder: 'justice', description: 'Procès aux assises (crimes)', states: ['mise-en-accusation', 'constitution-jury', 'proces', 'verdict'], contextFields: { accuse: 'string', crime: 'string' }, events: ['ACCUSER', 'JUGER', 'VERDICT'] },
  { id: 'appelJugement', name: 'Appel d\'un Jugement', category: 'justice', folder: 'justice', description: 'Procédure d\'appel', states: ['declaration-appel', 'instruction-appel', 'audience', 'arret'], contextFields: { appelant: 'string', jugementInitial: 'string' }, events: ['FAIRE-APPEL', 'INSTRUIRE', 'JUGER'] },
  { id: 'pourvoi Cassation', name: 'Pourvoi en Cassation', category: 'justice', folder: 'justice', description: 'Recours devant Cour de Cassation', states: ['pourvoi', 'memoire', 'examen', 'arret'], contextFields: { demandeur: 'string', moyen: 'string' }, events: ['POURVOIR', 'EXAMINER', 'ARRETER'] },
  { id: 'justiceMineurs', name: 'Justice des Mineurs', category: 'justice', folder: 'justice', description: 'Tribunal de la jeunesse', states: ['signalement', 'enquete-sociale', 'audience', 'mesure-educative'], contextFields: { mineur: 'string', age: 'number', faits: 'string' }, events: ['SIGNALER', 'ENQUETER', 'JUGER'] },
  { id: 'tribunalFamille', name: 'Tribunal de la Famille', category: 'justice', folder: 'justice', description: 'Affaires familiales', states: ['requete', 'tentative-conciliation', 'audience', 'jugement'], contextFields: { parties: 'string[]', objet: 'string' }, events: ['SAISIR', 'CONCILIER', 'JUGER'] },
  { id: 'autoriteParentale', name: 'Autorité Parentale', category: 'justice', folder: 'justice', description: 'Litiges autorité parentale', states: ['requete', 'enquete-sociale', 'audience', 'decision'], contextFields: { parents: 'string[]', enfants: 'number' }, events: ['SAISIR', 'ENQUETER', 'STATUER'] },
  { id: 'gardeEnfantsLitige', name: 'Garde des Enfants (litige)', category: 'justice', folder: 'justice', description: 'Fixation garde après séparation', states: ['demande', 'mediation', 'expertise', 'jugement'], contextFields: { parents: 'string[]', enfants: 'number' }, events: ['DEMANDER', 'MEDIER', 'JUGER'] },
  { id: 'pensionAlimentaireDemande', name: 'Pension Alimentaire', category: 'justice', folder: 'justice', description: 'Fixation pension alimentaire', states: ['demande', 'evaluation-ressources', 'audience', 'fixation'], contextFields: { creancier: 'string', debiteur: 'string' }, events: ['DEMANDER', 'EVALUER', 'FIXER'] },
  { id: 'adoptionProcedure', name: 'Adoption', category: 'justice', folder: 'justice', description: 'Procédure d\'adoption', states: ['agrement', 'apparentement', 'placement', 'jugement-adoption'], contextFields: { adoptants: 'string[]', enfant: 'string' }, events: ['AGREER', 'PLACER', 'ADOPTER'] },
  { id: 'successionPartage', name: 'Succession et Partage', category: 'justice', folder: 'justice', description: 'Règlement succession', states: ['ouverture', 'inventaire', 'liquidation', 'partage'], contextFields: { defunt: 'string', heritiers: 'string[]' }, events: ['OUVRIR', 'INVENTORIER', 'PARTAGER'] },
  { id: 'testamentConteste', name: 'Contestation Testament', category: 'justice', folder: 'justice', description: 'Litige sur testament', states: ['contestation', 'expertise', 'debats', 'jugement'], contextFields: { testateur: 'string', contestataires: 'string[]' }, events: ['CONTESTER', 'EXPERTISER', 'JUGER'] },
  { id: 'tutelleMajeurProtege', name: 'Tutelle Majeur Protégé', category: 'justice', folder: 'justice', description: 'Mesure de protection juridique', states: ['requete', 'expertise-medicale', 'audition', 'jugement'], contextFields: { personne: 'string', tuteur: 'string' }, events: ['REQUERIR', 'EXPERTISER', 'PROTEGER'] },
  { id: 'curatelle', name: 'Curatelle', category: 'justice', folder: 'justice', description: 'Mesure de curatelle', states: ['demande', 'evaluation', 'nomination-curateur', 'controle'], contextFields: { personne: 'string', curateur: 'string' }, events: ['DEMANDER', 'NOMMER', 'CONTROLER'] },
  { id: 'saisieImmobiliere', name: 'Saisie Immobilière', category: 'justice', folder: 'justice', description: 'Vente forcée bien immobilier', states: ['commandement', 'procedure', 'vente-forcee', 'attribution'], contextFields: { creancier: 'string', debiteur: 'string', bien: 'string' }, events: ['COMMANDER', 'SAISIR', 'VENDRE'] },
  { id: 'saisieMobiliere', name: 'Saisie Mobilière', category: 'justice', folder: 'justice', description: 'Saisie de biens meubles', states: ['titre-executoire', 'commandement', 'saisie', 'vente'], contextFields: { creancier: 'string', debiteur: 'string' }, events: ['COMMANDER', 'SAISIR'] },
  { id: 'saisieArret', name: 'Saisie-Arrêt Salaire', category: 'justice', folder: 'justice', description: 'Saisie sur salaire', states: ['autorisation', 'notification', 'retenues', 'versement'], contextFields: { creancier: 'string', debiteur: 'string', montant: 'number' }, events: ['AUTORISER', 'RETENIR'] },
  { id: 'expulsionLocataire', name: 'Expulsion Locataire', category: 'justice', folder: 'justice', description: 'Procédure d\'expulsion', states: ['conge', 'commandement', 'jugement-expulsion', 'execution'], contextFields: { bailleur: 'string', locataire: 'string' }, events: ['CONGEDIER', 'ASSIGNER', 'EXPULSER'] },
  { id: 'litigeBailleur', name: 'Litige Bailleur-Locataire', category: 'justice', folder: 'justice', description: 'Justice de Paix locatif', states: ['conciliation', 'audience', 'jugement'], contextFields: { bailleur: 'string', locataire: 'string', objet: 'string' }, events: ['CONCILIER', 'JUGER'] },
  { id: 'injonctionPayer', name: 'Injonction de Payer', category: 'justice', folder: 'justice', description: 'Recouvrement créances', states: ['requete', 'ordonnance', 'opposition-possible', 'execution'], contextFields: { creancier: 'string', debiteur: 'string', montant: 'number' }, events: ['REQUERIR', 'ORDONNER'] },
  { id: 'redressementJudiciaire', name: 'Redressement Judiciaire', category: 'justice', folder: 'justice', description: 'Faillite entreprise', states: ['ouverture', 'periode-observation', 'plan-redressement', 'execution'], contextFields: { entreprise: 'string', passif: 'number' }, events: ['OUVRIR', 'OBSERVER', 'REDRESSER'] },
  { id: 'liquidationJudiciaire', name: 'Liquidation Judiciaire', category: 'justice', folder: 'justice', description: 'Liquidation entreprise', states: ['jugement', 'inventaire', 'vente-actifs', 'repartition'], contextFields: { entreprise: 'string', liquidateur: 'string' }, events: ['PRONONCER', 'LIQUIDER'] },
  { id: 'refereCivil', name: 'Référé Civil', category: 'justice', folder: 'justice', description: 'Procédure d\'urgence', states: ['assignation', 'audience-rapide', 'ordonnance-refere'], contextFields: { demandeur: 'string', mesure-urgente: 'string' }, events: ['ASSIGNER', 'ORDONNER'] },
  { id: 'expertiseJudiciaire', name: 'Expertise Judiciaire', category: 'justice', folder: 'justice', description: 'Nomination expert par tribunal', states: ['ordonnance', 'mission', 'operations-expertise', 'rapport'], contextFields: { expert: 'string', objet: 'string' }, events: ['DESIGNER', 'EXPERTISER', 'RAPPORTER'] },
  { id: 'mediation Judiciaire', name: 'Médiation Judiciaire', category: 'justice', folder: 'justice', description: 'Médiation ordonnée par juge', states: ['ordonnance', 'seances-mediation', 'accord-ou-echec'], contextFields: { parties: 'string[]', mediateur: 'string' }, events: ['ORDONNER', 'MEDIER'] },
  { id: 'mesureEnquete', name: 'Mesure d\'Enquête', category: 'justice', folder: 'justice', description: 'Enquête sociale ordonnée', states: ['ordonnance', 'enquete', 'rapport', 'audience'], contextFields: { enqueteur: 'string', objet: 'string' }, events: ['ORDONNER', 'ENQUETER'] },
  { id: 'administrationProvisoire', name: 'Administration Provisoire', category: 'justice', folder: 'justice', description: 'Gestion provisoire biens', states: ['requete', 'designation', 'gestion', 'reddition-comptes'], contextFields: { administrateur: 'string', biens: 'string' }, events: ['DESIGNER', 'GERER'] },
  { id: 'sequestre Judiciaire', name: 'Séquestre Judiciaire', category: 'justice', folder: 'justice', description: 'Mise sous séquestre', states: ['ordonnance', 'consignation', 'conservation', 'main-levee'], contextFields: { bien: 'string', gardien: 'string' }, events: ['ORDONNER', 'CONSERVER'] },
  { id: 'sursis Probatoire', name: 'Sursis Probatoire', category: 'justice', folder: 'justice', description: 'Sursis avec mise à l\'épreuve', states: ['jugement-sursis', 'obligations', 'periode-epreuve', 'bilan'], contextFields: { condamne: 'string', duree: 'number', obligations: 'string[]' }, events: ['PRONONCER', 'CONTROLER'] },
  { id: 'amenagementPeine', name: 'Aménagement de Peine', category: 'justice', folder: 'justice', description: 'Semi-liberté, bracelet électronique', states: ['demande', 'enquete', 'debat-contradictoire', 'decision'], contextFields: { detenu: 'string', peine-restante: 'number' }, events: ['DEMANDER', 'EVALUER', 'AMENAGER'] },
  { id: 'liberationConditionnelle', name: 'Libération Conditionnelle', category: 'justice', folder: 'justice', description: 'Sortie anticipée de prison', states: ['eligibilite', 'demande', 'commission', 'liberation'], contextFields: { detenu: 'string', peine-effectuee: 'number' }, events: ['DEMANDER', 'EVALUER', 'LIBERER'] },
  { id: 'reductionPeine', name: 'Réduction de Peine', category: 'justice', folder: 'justice', description: 'Remise de peine pour bonne conduite', states: ['proposition', 'examen', 'decision'], contextFields: { detenu: 'string', reduction: 'number' }, events: ['PROPOSER', 'ACCORDER'] },
  { id: 'rehabilitationCasierJudiciaire', name: 'Réhabilitation', category: 'justice', folder: 'justice', description: 'Effacement casier judiciaire', states: ['delai-ecoule', 'demande', 'verification', 'rehabilitation'], contextFields: { personne: 'string', condamnations: 'string[]' }, events: ['DEMANDER', 'VERIFIER', 'REHABILITER'] },
  { id: 'aideJuridiqueGratuite', name: 'Aide Juridique Gratuite', category: 'justice', folder: 'justice', description: 'Pro Deo / Aide juridique', states: ['demande', 'examen-ressources', 'decision', 'designation-avocat'], contextFields: { demandeur: 'string', revenus: 'number' }, events: ['DEMANDER', 'EVALUER', 'ACCORDER'] },
  { id: 'commissionOfficeAvocat', name: 'Avocat Commis d\'Office', category: 'justice', folder: 'justice', description: 'Désignation avocat d\'office', states: ['demande', 'designation', 'mission'], contextFields: { client: 'string', avocat: 'string' }, events: ['DEMANDER', 'DESIGNER'] },
  { id: 'victimesIndemnisation', name: 'Indemnisation Victimes', category: 'justice', folder: 'justice', description: 'Commission Indemnisation Victimes', states: ['demande', 'instruction', 'evaluation-prejudice', 'indemnisation'], contextFields: { victime: 'string', prejudice: 'number' }, events: ['DEMANDER', 'EVALUER', 'INDEMNISER'] },
  { id: 'protectionTemoins', name: 'Protection des Témoins', category: 'justice', folder: 'justice', description: 'Mesures protection témoins', states: ['evaluation-menace', 'mesures-protection', 'accompagnement'], contextFields: { temoin: 'string', niveau-menace: 'string' }, events: ['EVALUER', 'PROTEGER'] },
  { id: 'expertisePsychiatrique', name: 'Expertise Psychiatrique Pénale', category: 'justice', folder: 'justice', description: 'Évaluation responsabilité pénale', states: ['ordonnance', 'examens', 'rapport-expertise'], contextFields: { personne: 'string', expert: 'string' }, events: ['ORDONNER', 'EXAMINER'] },
  { id: 'internementPsychiatrique', name: 'Internement Psychiatrique', category: 'justice', folder: 'justice', description: 'Mesure d\'internement', states: ['expertise', 'decision-internement', 'placement', 'revisions-periodiques'], contextFields: { personne: 'string', etablissement: 'string' }, events: ['EXPERTISER', 'INTERNER', 'REVISER'] },
  { id: 'extraditionDemande', name: 'Demande d\'Extradition', category: 'justice', folder: 'justice', description: 'Procédure extradition', states: ['mandat-arret-europeen', 'arrestation', 'audience', 'remise'], contextFields: { personne: 'string', etat-demandeur: 'string' }, events: ['EMETTRE-MAE', 'ARRETER', 'EXTRADER'] },
  { id: 'entraidePenaleInternationale', name: 'Entraide Pénale Internationale', category: 'justice', folder: 'justice', description: 'Commission rogatoire internationale', states: ['demande', 'transmission', 'execution', 'restitution'], contextFields: { etat-requete: 'string', actes: 'string' }, events: ['DEMANDER', 'EXECUTER'] },
  { id: 'confiscationAvoirs', name: 'Confiscation d\'Avoirs', category: 'justice', folder: 'justice', description: 'Saisie et confiscation biens criminels', states: ['gel-avoirs', 'enquete-patrimoniale', 'confiscation', 'affectation'], contextFields: { condamne: 'string', avoirs: 'number' }, events: ['GELER', 'CONFISQUER'] },
  { id: 'blanchimentArgent', name: 'Lutte contre Blanchiment', category: 'justice', folder: 'justice', description: 'Procédure anti-blanchiment', states: ['declaration-soupcon', 'enquete-ctif', 'gel-fonds', 'poursuites'], contextFields: { suspect: 'string', montant: 'number' }, events: ['DECLARER', 'ENQUETER', 'GELER'] },
  { id: 'cybercrimePoursuite', name: 'Cybercriminalité', category: 'justice', folder: 'justice', description: 'Poursuites infractions numériques', states: ['plainte', 'investigations-numeriques', 'perquisitions-serveurs', 'poursuites'], contextFields: { victime: 'string', type-cybercrime: 'string' }, events: ['PLAINTE', 'INVESTIGUER', 'POURSUIVRE'] },

  // ENVIRONNEMENT ET DÉVELOPPEMENT DURABLE (40 machines)
  { id: 'certificatPEB', name: 'Certificat PEB', category: 'environment', folder: 'environment', description: 'Performance énergétique bâtiment', states: ['demande', 'visite-certificateur', 'calcul-peb', 'emission-certificat'], contextFields: { bien: 'string', score: 'string' }, events: ['DEMANDER', 'VISITER', 'CERTIFIER'] },
  { id: 'primeRenovationEnergetique', name: 'Prime Rénovation Énergétique', category: 'environment', folder: 'environment', description: 'Aide rénovation énergétique', states: ['audit-energetique', 'devis', 'demande-prime', 'travaux', 'controle', 'paiement'], contextFields: { demandeur: 'string', montant: 'number' }, events: ['AUDITER', 'DEMANDER', 'REALISER'] },
  { id: 'panneauxSolairesInstallation', name: 'Installation Panneaux Solaires', category: 'environment', folder: 'environment', description: 'Aide panneaux photovoltaïques', states: ['etude-faisabilite', 'devis', 'permis', 'installation', 'raccordement', 'certificats-verts'], contextFields: { installation: 'string', puissance: 'number' }, events: ['ETUDIER', 'INSTALLER', 'RACCORDER'] },
  { id: 'certificatsVerts', name: 'Certificats Verts', category: 'environment', folder: 'environment', description: 'Octroi certificats verts électricité renouvelable', states: ['production', 'comptage', 'demande-certificats', 'octroi'], contextFields: { producteur: 'string', mwh: 'number' }, events: ['PRODUIRE', 'DEMANDER', 'OCTROYER'] },
  { id: 'pompesChaleurSubvention', name: 'Subvention Pompe à Chaleur', category: 'environment', folder: 'environment', description: 'Aide installation pompe chaleur', states: ['diagnostic', 'devis', 'demande', 'installation', 'controle'], contextFields: { demandeur: 'string', type: 'string' }, events: ['DIAGNOSTIQUER', 'DEMANDER', 'INSTALLER'] },
  { id: 'isolationThermique', name: 'Prime Isolation Thermique', category: 'environment', folder: 'environment', description: 'Aide isolation toiture, murs, sols', states: ['audit', 'devis', 'demande', 'travaux', 'attestation'], contextFields: { demandeur: 'string', surface: 'number' }, events: ['AUDITER', 'DEMANDER', 'ISOLER'] },
  { id: 'chaudiereCondensat ionPrime', name: 'Prime Chaudière Condensation', category: 'environment', folder: 'environment', description: 'Remplacement chaudière', states: ['diagnostic', 'devis', 'demande', 'installation', 'verification'], contextFields: { demandeur: 'string', ancienne-chaudiere: 'string' }, events: ['DIAGNOSTIQUER', 'INSTALLER'] },
  { id: 'citernes EauPluie', name: 'Subvention Citerne Eau de Pluie', category: 'environment', folder: 'environment', description: 'Aide installation citerne eau pluviale', states: ['projet', 'devis', 'demande', 'installation', 'controle'], contextFields: { demandeur: 'string', capacite: 'number' }, events: ['DEMANDER', 'INSTALLER'] },
  { id: 'compteurIntelligent', name: 'Compteur Intelligent', category: 'environment', folder: 'environment', description: 'Installation compteur numérique', states: ['eligibilite', 'planification', 'installation', 'activation'], contextFields: { client: 'string', type: 'electrique | gaz' }, events: ['PLANIFIER', 'INSTALLER'] },
  { id: 'vehiculeElectriquePrime', name: 'Prime Véhicule Électrique', category: 'environment', folder: 'environment', description: 'Aide achat voiture électrique', states: ['achat', 'demande-prime', 'verification', 'paiement'], contextFields: { acheteur: 'string', vehicule: 'string' }, events: ['ACHETER', 'DEMANDER'] },
  { id: 'borneRechargeInstallation', name: 'Borne de Recharge Électrique', category: 'environment', folder: 'environment', description: 'Installation wallbox domicile', states: ['demande', 'devis', 'installation', 'raccordement'], contextFields: { demandeur: 'string', puissance: 'number' }, events: ['DEMANDER', 'INSTALLER'] },
  { id: 'veloElectriquePrime', name: 'Prime Vélo Électrique', category: 'environment', folder: 'environment', description: 'Aide achat vélo électrique', states: ['achat', 'demande', 'verification', 'paiement'], contextFields: { acheteur: 'string', prix: 'number' }, events: ['ACHETER', 'DEMANDER'] },
  { id: 'triSelectifPoubelles', name: 'Tri Sélectif et Collecte', category: 'environment', folder: 'environment', description: 'Organisation collecte déchets', states: ['inscription', 'livraison-conteneurs', 'collecte-reguliere'], contextFields: { menage: 'string', types-dechets: 'string[]' }, events: ['INSCRIRE', 'COLLECTER'] },
  { id: 'parcConteneursRecyclage', name: 'Parc à Conteneurs', category: 'environment', folder: 'environment', description: 'Accès déchèterie', states: ['inscription', 'carte-acces', 'depot-dechets'], contextFields: { citoyen: 'string', commune: 'string' }, events: ['INSCRIRE', 'DEPOSER'] },
  { id: 'compostageCollectif', name: 'Compostage Collectif', category: 'environment', folder: 'environment', description: 'Composteur de quartier', states: ['projet', 'subvention', 'installation', 'gestion'], contextFields: { quartier: 'string', participants: 'number' }, events: ['PROPOSER', 'INSTALLER', 'GERER'] },
  { id: 'composteurIndividuel', name: 'Composteur Individuel', category: 'environment', folder: 'environment', description: 'Subvention composteur domicile', states: ['demande', 'livraison', 'formation'], contextFields: { demandeur: 'string' }, events: ['DEMANDER', 'LIVRER'] },
  { id: 'gestionEauxUsees', name: 'Assainissement Eaux Usées', category: 'environment', folder: 'environment', description: 'Raccordement égouts ou épuration individuelle', states: ['diagnostic', 'travaux', 'raccordement', 'controle'], contextFields: { habitation: 'string', type: 'collectif | individuel' }, events: ['DIAGNOSTIQUER', 'RACCORDER'] },
  { id: 'systemeEpurationIndividuel', name: 'Système Épuration Individuel', category: 'environment', folder: 'environment', description: 'Station épuration autonome', states: ['etude-sol', 'permis', 'installation', 'controle-periodique'], contextFields: { habitation: 'string', capacite: 'number' }, events: ['ETUDIER', 'INSTALLER', 'CONTROLER'] },
  { id: 'zoneBassesEmissions', name: 'Zone Basses Émissions (LEZ)', category: 'environment', folder: 'environment', description: 'Enregistrement véhicule LEZ', states: ['verification-norme', 'enregistrement', 'badge', 'acces-autorise'], contextFields: { vehicule: 'string', norme: 'string' }, events: ['VERIFIER', 'ENREGISTRER'] },
  { id: 'primeConversionVoiture', name: 'Prime Conversion Voiture', category: 'environment', folder: 'environment', description: 'Aide destruction vieux véhicule', states: ['destruction-ancien', 'achat-neuf', 'demande-prime', 'paiement'], contextFields: { ancien: 'string', nouveau: 'string' }, events: ['DETRUIRE', 'ACHETER', 'DEMANDER'] },
  { id: 'diagnosticAmiante', name: 'Diagnostic Amiante', category: 'environment', folder: 'environment', description: 'Inventaire amiante bâtiment', states: ['demande', 'inspection', 'prelevement', 'rapport'], contextFields: { batiment: 'string', expert: 'string' }, events: ['DEMANDER', 'INSPECTER'] },
  { id: 'desamiantage', name: 'Désamiantage', category: 'environment', folder: 'environment', description: 'Retrait amiante', states: ['diagnostic', 'plan-travail', 'desamiantage', 'controle-air', 'certificat'], contextFields: { chantier: 'string', entreprise: 'string' }, events: ['PLANIFIER', 'RETIRER', 'CONTROLER'] },
  { id: 'pollutionSolDepollution', name: 'Dépollution Sol', category: 'environment', folder: 'environment', description: 'Assainissement sol pollué', states: ['etude-pollution', 'plan-assainissement', 'travaux', 'controle-final'], contextFields: { site: 'string', polluants: 'string[]' }, events: ['ETUDIER', 'ASSAINIR'] },
  { id: 'declarationSitesPollues', name: 'Déclaration Sites Pollués', category: 'environment', folder: 'environment', description: 'Inventaire sites contaminés', states: ['identification', 'declaration', 'investigation', 'inscription-registre'], contextFields: { site: 'string', activite-passee: 'string' }, events: ['IDENTIFIER', 'DECLARER'] },
  { id: 'etudeImpactEnvironnemental', name: 'Étude d\'Impact Environnemental', category: 'environment', folder: 'environment', description: 'EIE pour grands projets', states: ['cadrage', 'etude', 'enquete-publique', 'avis'], contextFields: { projet: 'string', bureau-etude: 'string' }, events: ['CADRER', 'ETUDIER', 'CONSULTER'] },
  { id: 'natura2000Protection', name: 'Protection Natura 2000', category: 'environment', folder: 'environment', description: 'Zones Natura 2000', states: ['designation', 'plan-gestion', 'surveillance', 'conservation'], contextFields: { zone: 'string', superficie: 'number' }, events: ['DESIGNER', 'GERER', 'SURVEILLER'] },
  { id: 'reserveNaturelleCreation', name: 'Création Réserve Naturelle', category: 'environment', folder: 'environment', description: 'Classement réserve naturelle', states: ['proposition', 'enquete-publique', 'arrete-classement', 'gestion'], contextFields: { zone: 'string', gestionnaire: 'string' }, events: ['PROPOSER', 'CLASSER'] },
  { id: 'protectionArbreRemarquable', name: 'Protection Arbre Remarquable', category: 'environment', folder: 'environment', description: 'Classement arbres remarquables', states: ['signalement', 'expertise', 'classement', 'protection'], contextFields: { arbre: 'string', commune: 'string' }, events: ['SIGNALER', 'CLASSER'] },
  { id: 'permisAbattageArbre', name: 'Permis d\'Abattage Arbre', category: 'environment', folder: 'environment', description: 'Autorisation abattage', states: ['demande', 'visite-terrain', 'decision', 'compensation'], contextFields: { demandeur: 'string', arbre: 'string' }, events: ['DEMANDER', 'AUTORISER'] },
  { id: 'inondationsPreventionPlan', name: 'Plan Prévention Inondations', category: 'environment', folder: 'environment', description: 'Gestion risque inondation', states: ['cartographie-risque', 'mesures-prevention', 'alerte', 'intervention'], contextFields: { zone: 'string', niveau-risque: 'string' }, events: ['CARTOGRAPHIER', 'PREVENIR'] },
  { id: 'captageEauProtection', name: 'Protection Captage d\'Eau', category: 'environment', folder: 'environment', description: 'Zones protection captage', states: ['delimitation', 'reglementation', 'surveillance'], contextFields: { captage: 'string', perimetre: 'number' }, events: ['DELIMITER', 'REGLEMENTER'] },
  { id: 'qualiteEauPotable', name: 'Contrôle Qualité Eau Potable', category: 'environment', folder: 'environment', description: 'Surveillance qualité eau distribution', states: ['prelevement', 'analyse', 'interpretation', 'publication'], contextFields: { reseau: 'string', parametres: 'string[]' }, events: ['PRELEVER', 'ANALYSER'] },
  { id: 'qualiteAirSurveillance', name: 'Surveillance Qualité de l\'Air', category: 'environment', folder: 'environment', description: 'Monitoring pollution atmosphérique', states: ['mesure', 'analyse', 'alerte-seuils', 'publication'], contextFields: { station: 'string', polluants: 'string[]' }, events: ['MESURER', 'ALERTER'] },
  { id: 'bruitNuisancesSonores', name: 'Nuisances Sonores', category: 'environment', folder: 'environment', description: 'Gestion pollution sonore', states: ['plainte', 'mesurage', 'constat-infraction', 'sanction'], contextFields: { plaignant: 'string', source: 'string' }, events: ['PLAINTE', 'MESURER', 'SANCTIONNER'] },
  { id: 'planClimatCommunal', name: 'Plan Climat Communal', category: 'environment', folder: 'environment', description: 'PAEDC Plan Energie Climat', states: ['diagnostic', 'objectifs', 'actions', 'suivi'], contextFields: { commune: 'string', objectif-reduction: 'number' }, events: ['DIAGNOSTIQUER', 'PLANIFIER', 'SUIVRE'] },
  { id: 'bilanCarboneEntreprise', name: 'Bilan Carbone Entreprise', category: 'environment', folder: 'environment', description: 'Calcul empreinte carbone', states: ['perimetre', 'collecte-donnees', 'calcul', 'plan-reduction'], contextFields: { entreprise: 'string', emissions: 'number' }, events: ['DEFINIR', 'CALCULER', 'REDUIRE'] },
  { id: 'eco nomieCirculaire', name: 'Subvention Économie Circulaire', category: 'environment', folder: 'environment', description: 'Aide projets économie circulaire', states: ['projet', 'dossier', 'evaluation', 'subvention'], contextFields: { porteur: 'string', montant: 'number' }, events: ['PROPOSER', 'EVALUER', 'FINANCER'] },
  { id: 'labelEcologique', name: 'Label Écologique', category: 'environment', folder: 'environment', description: 'Certification environnementale produits', states: ['demande', 'audit', 'verification', 'certification'], contextFields: { entreprise: 'string', produit: 'string' }, events: ['DEMANDER', 'AUDITER', 'CERTIFIER'] },
  { id: 'rapportDurabiliteRSE', name: 'Rapport Durabilité RSE', category: 'environment', folder: 'environment', description: 'Reporting extra-financier', states: ['collecte-donnees', 'redaction', 'verification', 'publication'], contextFields: { entreprise: 'string', annee: 'number' }, events: ['COLLECTER', 'REDIGER', 'PUBLIER'] },
  { id: 'biodiversiteEntreprise', name: 'Biodiversité en Entreprise', category: 'environment', folder: 'environment', description: 'Gestion écologique sites entreprise', states: ['diagnostic-biodiversite', 'plan-action', 'amenagements', 'suivi'], contextFields: { entreprise: 'string', site: 'string' }, events: ['DIAGNOSTIQUER', 'AMENAGER'] },

  // COMMERCE ET ENTREPRISES (50 machines) - Continuation
  { id: 'inscriptionBCE', name: 'Inscription BCE', category: 'commerce', folder: 'commerce', description: 'Banque-Carrefour Entreprises', states: ['depot-dossier', 'verification', 'attribution-numero', 'publication'], contextFields: { entreprise: 'string', activite: 'string' }, events: ['DEPOSER', 'VERIFIER', 'ATTRIBUER'] },
  { id: 'modificationsStatuts', name: 'Modification Statuts', category: 'commerce', folder: 'commerce', description: 'Changement statuts société', states: ['ag-extraordinaire', 'redaction', 'notaire', 'depot-greffe', 'publication'], contextFields: { societe: 'string', modifications: 'string[]' }, events: ['CONVOQUER', 'MODIFIER', 'PUBLIER'] },
  { id: 'augmentationCapital', name: 'Augmentation Capital', category: 'commerce', folder: 'commerce', description: 'Augmentation capital social', states: ['ag', 'souscription', 'liberation', 'modification-statuts', 'publication'], contextFields: { societe: 'string', montant: 'number' }, events: ['DECIDER', 'SOUSCRIRE', 'LIBERER'] },
  { id: 'cessationActivite', name: 'Cessation d\'Activité', category: 'commerce', folder: 'commerce', description: 'Fermeture entreprise', states: ['decision', 'liquidation', 'radiation-bce', 'radiation-tva'], contextFields: { entreprise: 'string' }, events: ['DECIDER', 'LIQUIDER', 'RADIER'] },
  { id: 'failliteDeclaration', name: 'Déclaration Faillite', category: 'commerce', folder: 'commerce', description: 'Procédure faillite', states: ['depot-bilan', 'jugement', 'curateur', 'liquidation'], contextFields: { entreprise: 'string', passif: 'number' }, events: ['DEPOSER', 'JUGER', 'LIQUIDER'] },
  { id: 'concordatJudiciaire', name: 'Concordat Judiciaire', category: 'commerce', folder: 'commerce', description: 'Réorganisation judiciaire', states: ['demande', 'sursis', 'plan-reorganisation', 'homologation'], contextFields: { entreprise: 'string', creanciers: 'string[]' }, events: ['DEMANDER', 'PLANIFIER', 'HOMOLOGUER'] },
  { id: 'licenceCommerciale', name: 'Licence Commerciale', category: 'commerce', folder: 'commerce', description: 'Autorisation d\'exploitation', states: ['demande', 'verification', 'delivrance'], contextFields: { commercial: 'string', secteur: 'string' }, events: ['DEMANDER', 'VERIFIER', 'DELIVRER'] },
  { id: 'autorisation HorecaExploitation', name: 'Autorisation Horeca', category: 'commerce', folder: 'commerce', description: 'Licence d\'exploitation Horeca', states: ['formation-obligatoire', 'demande', 'inspection', 'autorisation'], contextFields: { exploitant: 'string', etablissement: 'string' }, events: ['FORMER', 'DEMANDER', 'AUTORISER'] },
  { id: 'hygiene FoodABCA', name: 'Autocontrôle AFSCA', category: 'commerce', folder: 'commerce', description: 'Système autocontrôle alimentaire', states: ['formation-haccp', 'mise-en-place', 'controle-afsca', 'certification'], contextFields: { etablissement: 'string', type: 'string' }, events: ['FORMER', 'METTRE-EN-PLACE', 'CONTROLER'] },
  { id: 'franchisageContrat', name: 'Contrat de Franchise', category: 'commerce', folder: 'commerce', description: 'Création franchise', states: ['negociation', 'doc-information-prealable', 'signature', 'formation'], contextFields: { franchiseur: 'string', franchise: 'string' }, events: ['NEGOCIER', 'INFORMER', 'SIGNER'] },
  { id: 'marqueDenomCommerciale', name: 'Marque et Dénomination', category: 'commerce', folder: 'commerce', description: 'Protection marque commerciale', states: ['recherche-anteriorite', 'depot', 'examen', 'enregistrement'], contextFields: { marque: 'string', classes: 'number[]' }, events: ['RECHERCHER', 'DEPOSER', 'ENREGISTRER'] },
  { id: 'brevetInvention', name: 'Brevet d\'Invention', category: 'commerce', folder: 'commerce', description: 'Protection propriété intellectuelle', states: ['depot-demande', 'examen-forme', 'publication', 'delivrance'], contextFields: { inventeur: 'string', invention: 'string' }, events: ['DEPOSER', 'EXAMINER', 'DELIVRER'] },
  { id: 'droitAuteur', name: 'Protection Droit d\'Auteur', category: 'commerce', folder: 'commerce', description: 'Enregistrement œuvre', states: ['creation', 'depot-sabam-ou-autre', 'protection'], contextFields: { auteur: 'string', oeuvre: 'string' }, events: ['CREER', 'DEPOSER'] },
  { id: 'designModele', name: 'Protection Design/Modèle', category: 'commerce', folder: 'commerce', description: 'Enregistrement design produit', states: ['depot', 'examen', 'enregistrement'], contextFields: { createur: 'string', design: 'string' }, events: ['DEPOSER', 'ENREGISTRER'] },
  { id: 'bailCommercial', name: 'Bail Commercial', category: 'commerce', folder: 'commerce', description: 'Location locale commercial', states: ['negociation', 'etat-lieux', 'signature', 'enregistrement'], contextFields: { bailleur: 'string', locataire: 'string', loyer: 'number' }, events: ['NEGOCIER', 'SIGNER', 'ENREGISTRER'] },
  { id: 'cessionFondsCommerce', name: 'Cession Fonds de Commerce', category: 'commerce', folder: 'commerce', description: 'Vente activité commerciale', states: ['negociation', 'due-diligence', 'acte-vente', 'publicite-legale'], contextFields: { vendeur: 'string', acheteur: 'string', prix: 'number' }, events: ['NEGOCIER', 'VENDRE', 'PUBLIER'] },
  { id: 'comptabiliteAnnuelle', name: 'Comptes Annuels', category: 'commerce', folder: 'commerce', description: 'Dépôt comptes annuels', states: ['cloture-exercice', 'etablissement-comptes', 'approbation-ag', 'depot-bce'], contextFields: { societe: 'string', exercice: 'number' }, events: ['CLOTURER', 'APPROUVER', 'DEPOSER'] },
  { id: 'controleReviseur', name: 'Contrôle Commissaire', category: 'commerce', folder: 'commerce', description: 'Audit par réviseur d\'entreprise', states: ['nomination', 'controle-comptes', 'rapport', 'ag'], contextFields: { societe: 'string', reviseur: 'string' }, events: ['NOMMER', 'AUDITER', 'RAPPORTER'] },
  { id: 'assemblee GeneraleOrdinaire', name: 'Assemblée Générale Ordinaire', category: 'commerce', folder: 'commerce', description: 'AG annuelle obligatoire', states: ['convocation', 'ordre-jour', 'tenue-ag', 'pv'], contextFields: { societe: 'string', actionnaires: 'string[]' }, events: ['CONVOQUER', 'TENIR'] },
  { id: 'dividendesDistribution', name: 'Distribution Dividendes', category: 'commerce', folder: 'commerce', description: 'Versement dividendes actionnaires', states: ['approbation-comptes', 'decision-distribution', 'calcul', 'paiement'], contextFields: { societe: 'string', montant-total: 'number' }, events: ['DECIDER', 'CALCULER', 'PAYER'] },
  { id: 'fusionSocietes', name: 'Fusion de Sociétés', category: 'commerce', folder: 'commerce', description: 'Fusion entre entreprises', states: ['projet-fusion', 'rapport-gestion', 'approbation-ag', 'realisation'], contextFields: { absorbante: 'string', absorbee: 'string' }, events: ['PROJET', 'APPROUVER', 'REALISER'] },
  { id: 'scissionSociete', name: 'Scission de Société', category: 'commerce', folder: 'commerce', description: 'Division entreprise', states: ['projet-scission', 'evaluation', 'approbation', 'realisation'], contextFields: { societe: 'string', nouvelles: 'string[]' }, events: ['PROJET', 'EVALUER', 'SCINDER'] },
  { id: 'apportNature', name: 'Apport en Nature', category: 'commerce', folder: 'commerce', description: 'Apport non-monétaire au capital', states: ['designation-reviseur', 'evaluation', 'rapport', 'approbation'], contextFields: { societe: 'string', bien: 'string', valeur: 'number' }, events: ['EVALUER', 'APPROUVER'] },
  { id: 'conflitInterets', name: 'Conflit d\'Intérêts', category: 'commerce', folder: 'commerce', description: 'Procédure article 523 CSA', states: ['declaration', 'avis-commissaire', 'deliberation', 'publication'], contextFields: { societe: 'string', administrateur: 'string' }, events: ['DECLARER', 'DELIBERER'] },
  { id: 'responsabiliteAdministrateurs', name: 'Responsabilité Administrateurs', category: 'commerce', folder: 'commerce', description: 'Action en responsabilité', states: ['faute', 'dommage', 'action-justice', 'jugement'], contextFields: { societe: 'string', administrateur: 'string' }, events: ['CONSTATER', 'ASSIGNER'] },
  { id: 'nomina tionGerant', name: 'Nomination Gérant', category: 'commerce', folder: 'commerce', description: 'Désignation gérant société', states: ['candidature', 'verification', 'decision', 'publication'], contextFields: { societe: 'string', gerant: 'string' }, events: ['PROPOSER', 'NOMMER', 'PUBLIER'] },
  { id: 'revocationAdministrateur', name: 'Révocation Administrateur', category: 'commerce', folder: 'commerce', description: 'Fin mandat administrateur', states: ['convocation-ag', 'vote', 'notification', 'publication'], contextFields: { societe: 'string', administrateur: 'string' }, events: ['CONVOQUER', 'REVOQUER'] },
  { id: 'pacteActionnaires', name: 'Pacte d\'Actionnaires', category: 'commerce', folder: 'commerce', description: 'Accord entre actionnaires', states: ['negociation', 'redaction', 'signature'], contextFields: { societe: 'string', actionnaires: 'string[]' }, events: ['NEGOCIER', 'SIGNER'] },
  { id: 'clauseNonConcurrence', name: 'Clause Non-Concurrence', category: 'commerce', folder: 'commerce', description: 'Accord de non-concurrence', states: ['redaction', 'signature', 'respect-clause'], contextFields: { employeur: 'string', employe: 'string', duree: 'number' }, events: ['REDIGER', 'SIGNER', 'RESPECTER'] },
  { id: 'secretCommercial', name: 'Protection Secret Commercial', category: 'commerce', folder: 'commerce', description: 'Confidentialité informations', states: ['identification', 'mesures-protection', 'nda', 'surveillance'], contextFields: { entreprise: 'string', secret: 'string' }, events: ['IDENTIFIER', 'PROTEGER'] },
  { id: 'concurrenceDeloyale', name: 'Action Concurrence Déloyale', category: 'commerce', folder: 'commerce', description: 'Poursuite pratiques déloyales', states: ['constat', 'mise-en-demeure', 'action-justice', 'jugement'], contextFields: { plaignant: 'string', defendeur: 'string' }, events: ['CONSTATER', 'ASSIGNER'] },
  { id: 'cartelEntente', name: 'Contrôle Ententes/Cartels', category: 'commerce', folder: 'commerce', description: 'Autorité concurrence', states: ['enquete', 'grief', 'defense', 'decision-sanction'], contextFields: { entreprises: 'string[]', pratique: 'string' }, events: ['ENQUETER', 'SANCTIONNER'] },
  { id: 'abusPosotionDominante', name: 'Abus Position Dominante', category: 'commerce', folder: 'commerce', description: 'Contrôle monopoles', states: ['plainte', 'analyse-marche', 'instruction', 'sanction'], contextFields: { entreprise: 'string', marche: 'string' }, events: ['PLAINTE', 'ANALYSER', 'SANCTIONNER'] },
  { id: 'concentrationEntreprises', name: 'Contrôle Concentrations', category: 'commerce', folder: 'commerce', description: 'Autorisation fusion/acquisition', states: ['notification', 'examen-phase-1', 'phase-2-eventuelle', 'decision'], contextFields: { parties: 'string[]', chiffre-affaires: 'number' }, events: ['NOTIFIER', 'EXAMINER', 'AUTORISER'] },
  { id: 'aideDatatEtat', name: 'Aide d\'État', category: 'commerce', folder: 'commerce', description: 'Subvention publique entreprise', states: ['demande', 'verification-compatibilite', 'notification-ue', 'octroi'], contextFields: { entreprise: 'string', montant: 'number', objectif: 'string' }, events: ['DEMANDER', 'VERIFIER', 'OCTROYER'] },
  { id: 'marchePublic', name: 'Marché Public', category: 'commerce', folder: 'commerce', description: 'Soumission marché public', states: ['publication', 'offres', 'analyse', 'attribution'], contextFields: { autorite: 'string', objet: 'string', montant: 'number' }, events: ['PUBLIER', 'SOUMETTRE', 'ATTRIBUER'] },
  { id: 'subventionInnovation', name: 'Subvention Innovation', category: 'commerce', folder: 'commerce', description: 'Aide R&D', states: ['appel-projet', 'depot-dossier', 'evaluation', 'financement'], contextFields: { entreprise: 'string', projet: 'string' }, events: ['DEPOSER', 'EVALUER', 'FINANCER'] },
  { id: 'creditInvestissement', name: 'Crédit d\'Investissement', category: 'commerce', folder: 'commerce', description: 'Financement bancaire PME', states: ['demande', 'analyse-dossier', 'comite-credit', 'octroi'], contextFields: { emprunteur: 'string', montant: 'number' }, events: ['DEMANDER', 'ANALYSER', 'OCTROYER'] },
  { id: 'garantieRegionale', name: 'Garantie Régionale', category: 'commerce', folder: 'commerce', description: 'Garantie publique crédit PME', states: ['demande', 'analyse-risque', 'decision', 'garantie'], contextFields: { entreprise: 'string', credit: 'number' }, events: ['DEMANDER', 'ANALYSER', 'GARANTIR'] },
  { id: 'exportationAideCommerce', name: 'Aide à l\'Exportation', category: 'commerce', folder: 'commerce', description: 'Soutien commerce international', states: ['diagnostic-export', 'formation', 'prospection', 'accompagnement'], contextFields: { entreprise: 'string', pays-cible: 'string' }, events: ['DIAGNOSTIQUER', 'ACCOMPAGNER'] },
  { id: 'douaneDeclaration', name: 'Déclaration en Douane', category: 'commerce', folder: 'commerce', description: 'Import/export hors UE', states: ['declaration', 'verification', 'paiement-droits', 'dedouanement'], contextFields: { declarant: 'string', marchandise: 'string' }, events: ['DECLARER', 'VERIFIER', 'DEDOUANER'] },
  { id: 'tvaIntracommunautaire', name: 'TVA Intracommunautaire', category: 'commerce', folder: 'commerce', description: 'Transactions intra-UE', states: ['vente', 'declaration-intrastat', 'listing-client', 'controle'], contextFields: { vendeur: 'string', acheteur: 'string' }, events: ['VENDRE', 'DECLARER'] },
  { id: 'eanCodeBarres', name: 'Code-Barres EAN', category: 'commerce', folder: 'commerce', description: 'Attribution code produit', states: ['adhesion-gs1', 'attribution-prefixe', 'generation-codes'], contextFields: { entreprise: 'string', produits: 'number' }, events: ['ADHERER', 'ATTRIBUER'] },
  { id: 'normeISO9001', name: 'Certification ISO 9001', category: 'commerce', folder: 'commerce', description: 'Management qualité', states: ['mise-en-place', 'audit-blanc', 'audit-certification', 'certification'], contextFields: { entreprise: 'string', auditeur: 'string' }, events: ['IMPLEMENTER', 'AUDITER', 'CERTIFIER'] },
  { id: 'normeISO14001', name: 'Certification ISO 14001', category: 'commerce', folder: 'commerce', description: 'Management environnemental', states: ['diagnostic-environnemental', 'systeme-management', 'audit', 'certification'], contextFields: { entreprise: 'string' }, events: ['DIAGNOSTIQUER', 'METTRE-EN-PLACE', 'CERTIFIER'] },
  { id: 'haccp Certification', name: 'Certification HACCP', category: 'commerce', folder: 'commerce', description: 'Sécurité alimentaire', states: ['analyse-dangers', 'points-critiques', 'procedures', 'certification'], contextFields: { etablissement: 'string' }, events: ['ANALYSER', 'METTRE-EN-PLACE', 'CERTIFIER'] },
  { id: 'labelBio', name: 'Certification Bio', category: 'commerce', folder: 'commerce', description: 'Agriculture biologique', states: ['notification', 'conversion', 'controle', 'certification'], contextFields: { producteur: 'string', surface: 'number' }, events: ['NOTIFIER', 'CONVERTIR', 'CERTIFIER'] },
  { id: 'responsabiliteProduit', name: 'Responsabilité Produit Défectueux', category: 'commerce', folder: 'commerce', description: 'Rappel produit dangereux', states: ['detection-defaut', 'evaluation-risque', 'rappel', 'information-consommateurs'], contextFields: { fabricant: 'string', produit: 'string' }, events: ['DETECTER', 'RAPPELER', 'INFORMER'] },
];

function generateMachineFile(def: MachineDefinition): string {
  const contextType = Object.entries(def.contextFields)
    .map(([key, type]) => `  ${key}: ${type};`)
    .join('\n');

  const eventTypes = def.events.map(e => `| { type: '${e}' }`).join('\n      ');

  const statesCode = def.states.map(state => `
    ${state}: {
      on: {},
      meta: {
        description: 'État: ${state}',
      },
    },`).join('\n');

  return `/**
 * Machine XState pour ${def.name}
 * Catégorie: ${def.category}
 *
 * ${def.description}
 */

import { createMachine, assign } from 'xstate';

interface ${def.id.charAt(0).toUpperCase() + def.id.slice(1)}Context {
${contextType}
}

export const ${def.id}Machine = createMachine({
  id: '${def.id}',
  initial: '${def.states[0]}',

  schema: {
    context: {} as ${def.id.charAt(0).toUpperCase() + def.id.slice(1)}Context,
    events: {} as
      ${eventTypes}
  },

  context: {
    ${Object.keys(def.contextFields).map(k => `${k}: null`).join(',\n    ')}
  },

  states: {${statesCode}
  },
});
`;
}

// Création des dossiers et fichiers
const basePath = path.join(__dirname, '..', 'src', 'workflows');

for (const def of machinesDefinitions) {
  const folderPath = path.join(basePath, def.folder);

  // Créer le dossier si nécessaire
  if (!fs.existsSync(folderPath)) {
    fs.mkdirSync(folderPath, { recursive: true });
  }

  const filePath = path.join(folderPath, `${def.id}Machine.ts`);
  const content = generateMachineFile(def);

  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`✓ Créé: ${def.folder}/${def.id}Machine.ts`);
}

console.log(`\n✓ ${machinesDefinitions.length} machines générées avec succès!`);
